// Generated by CoffeeScript 1.12.7
(function() {
  exports.db = {
    host: "127.0.0.1",
    port: 6379,
    db: 0,
    pass: null
  };

  exports.sessiondb = {
    host: "127.0.0.1",
    port: 6379,
    db: 1,
    pass: null
  };

  exports.app = {
    port: 3000
  };

}).call(this);
