// Generated by CoffeeScript 1.6.1
(function() {

  exports.db = {
    host: "10.211.55.6",
    port: 6379,
    db: 0,
    pass: '123456'
  };

  exports.sessiondb = {
    host: "10.211.55.6",
    port: 6379,
    db: 1,
    pass: '123456'
  };

  exports.app = {
    port: 3000
  };

}).call(this);
