// Generated by CoffeeScript 1.6.1
(function() {
  var utils;

  utils = require('../utils');

  exports.index = function(req, res) {
    if (!utils.authenticateAdmin(req, res)) {
      return;
    }
    return res.render("admin/department");
  };

  exports.usersIndex = function(req, res) {
    if (!utils.authenticateAdmin(req, res)) {
      return;
    }
    return res.render("admin/users");
  };

  exports.admingroupIndex = function(req, res) {
    if (!utils.authenticateAdmin(req, res)) {
      return;
    }
    return res.render("admin/admingroup");
  };

}).call(this);
